language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
before_install:
  - npm i -g npm@5.2.0
install: 
  - npm install eslint eslint-config-aqua eslint-changes
script:
  - ./node_modules/.bin/eslint-changes